export default {
  login: "Dharanish-PM",
  id: 96013850,
  node_id: "U_kgDOBbkOGg",
  avatar_url: "https://avatars.githubusercontent.com/u/96013850?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Dharanish-PM",
  html_url: "https://github.com/Dharanish-PM",
  followers_url: "https://api.github.com/users/Dharanish-PM/followers",
  following_url:
    "https://api.github.com/users/Dharanish-PM/following{/other_user}",
  gists_url: "https://api.github.com/users/Dharanish-PM/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Dharanish-PM/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Dharanish-PM/subscriptions",
  organizations_url: "https://api.github.com/users/Dharanish-PM/orgs",
  repos_url: "https://api.github.com/users/Dharanish-PM/repos",
  events_url: "https://api.github.com/users/Dharanish-PM/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Dharanish-PM/received_events",
  type: "User",
  site_admin: false,
  name: "Dharanish P M",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 25,
  public_gists: 1,
  followers: 8,
  following: 2,
  created_at: "2021-12-12T15:16:43Z",
  updated_at: "2023-02-04T06:04:26Z",
};
