export default [
  {
    login: "hema1304",
    id: 65031135,
    node_id: "MDQ6VXNlcjY1MDMxMTM1",
    avatar_url: "https://avatars.githubusercontent.com/u/65031135?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hema1304",
    html_url: "https://github.com/hema1304",
    followers_url: "https://api.github.com/users/hema1304/followers",
    following_url:
      "https://api.github.com/users/hema1304/following{/other_user}",
    gists_url: "https://api.github.com/users/hema1304/gists{/gist_id}",
    starred_url: "https://api.github.com/users/hema1304/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hema1304/subscriptions",
    organizations_url: "https://api.github.com/users/hema1304/orgs",
    repos_url: "https://api.github.com/users/hema1304/repos",
    events_url: "https://api.github.com/users/hema1304/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hema1304/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "AshwanthramKL",
    id: 71945723,
    node_id: "MDQ6VXNlcjcxOTQ1NzIz",
    avatar_url: "https://avatars.githubusercontent.com/u/71945723?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AshwanthramKL",
    html_url: "https://github.com/AshwanthramKL",
    followers_url: "https://api.github.com/users/AshwanthramKL/followers",
    following_url:
      "https://api.github.com/users/AshwanthramKL/following{/other_user}",
    gists_url: "https://api.github.com/users/AshwanthramKL/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/AshwanthramKL/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/AshwanthramKL/subscriptions",
    organizations_url: "https://api.github.com/users/AshwanthramKL/orgs",
    repos_url: "https://api.github.com/users/AshwanthramKL/repos",
    events_url: "https://api.github.com/users/AshwanthramKL/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AshwanthramKL/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Gowtham2543",
    id: 74668263,
    node_id: "MDQ6VXNlcjc0NjY4MjYz",
    avatar_url: "https://avatars.githubusercontent.com/u/74668263?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Gowtham2543",
    html_url: "https://github.com/Gowtham2543",
    followers_url: "https://api.github.com/users/Gowtham2543/followers",
    following_url:
      "https://api.github.com/users/Gowtham2543/following{/other_user}",
    gists_url: "https://api.github.com/users/Gowtham2543/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Gowtham2543/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Gowtham2543/subscriptions",
    organizations_url: "https://api.github.com/users/Gowtham2543/orgs",
    repos_url: "https://api.github.com/users/Gowtham2543/repos",
    events_url: "https://api.github.com/users/Gowtham2543/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Gowtham2543/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Sanjay-21",
    id: 83592592,
    node_id: "MDQ6VXNlcjgzNTkyNTky",
    avatar_url: "https://avatars.githubusercontent.com/u/83592592?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Sanjay-21",
    html_url: "https://github.com/Sanjay-21",
    followers_url: "https://api.github.com/users/Sanjay-21/followers",
    following_url:
      "https://api.github.com/users/Sanjay-21/following{/other_user}",
    gists_url: "https://api.github.com/users/Sanjay-21/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Sanjay-21/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Sanjay-21/subscriptions",
    organizations_url: "https://api.github.com/users/Sanjay-21/orgs",
    repos_url: "https://api.github.com/users/Sanjay-21/repos",
    events_url: "https://api.github.com/users/Sanjay-21/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Sanjay-21/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "masif2002",
    id: 94846379,
    node_id: "U_kgDOBac9qw",
    avatar_url: "https://avatars.githubusercontent.com/u/94846379?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/masif2002",
    html_url: "https://github.com/masif2002",
    followers_url: "https://api.github.com/users/masif2002/followers",
    following_url:
      "https://api.github.com/users/masif2002/following{/other_user}",
    gists_url: "https://api.github.com/users/masif2002/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/masif2002/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/masif2002/subscriptions",
    organizations_url: "https://api.github.com/users/masif2002/orgs",
    repos_url: "https://api.github.com/users/masif2002/repos",
    events_url: "https://api.github.com/users/masif2002/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/masif2002/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "priyaskumar",
    id: 94846381,
    node_id: "U_kgDOBac9rQ",
    avatar_url: "https://avatars.githubusercontent.com/u/94846381?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/priyaskumar",
    html_url: "https://github.com/priyaskumar",
    followers_url: "https://api.github.com/users/priyaskumar/followers",
    following_url:
      "https://api.github.com/users/priyaskumar/following{/other_user}",
    gists_url: "https://api.github.com/users/priyaskumar/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/priyaskumar/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/priyaskumar/subscriptions",
    organizations_url: "https://api.github.com/users/priyaskumar/orgs",
    repos_url: "https://api.github.com/users/priyaskumar/repos",
    events_url: "https://api.github.com/users/priyaskumar/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/priyaskumar/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ShrikanthDeva",
    id: 94846398,
    node_id: "U_kgDOBac9vg",
    avatar_url: "https://avatars.githubusercontent.com/u/94846398?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ShrikanthDeva",
    html_url: "https://github.com/ShrikanthDeva",
    followers_url: "https://api.github.com/users/ShrikanthDeva/followers",
    following_url:
      "https://api.github.com/users/ShrikanthDeva/following{/other_user}",
    gists_url: "https://api.github.com/users/ShrikanthDeva/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ShrikanthDeva/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ShrikanthDeva/subscriptions",
    organizations_url: "https://api.github.com/users/ShrikanthDeva/orgs",
    repos_url: "https://api.github.com/users/ShrikanthDeva/repos",
    events_url: "https://api.github.com/users/ShrikanthDeva/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ShrikanthDeva/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "anilsurriya",
    id: 107798126,
    node_id: "U_kgDOBmzebg",
    avatar_url: "https://avatars.githubusercontent.com/u/107798126?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/anilsurriya",
    html_url: "https://github.com/anilsurriya",
    followers_url: "https://api.github.com/users/anilsurriya/followers",
    following_url:
      "https://api.github.com/users/anilsurriya/following{/other_user}",
    gists_url: "https://api.github.com/users/anilsurriya/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/anilsurriya/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/anilsurriya/subscriptions",
    organizations_url: "https://api.github.com/users/anilsurriya/orgs",
    repos_url: "https://api.github.com/users/anilsurriya/repos",
    events_url: "https://api.github.com/users/anilsurriya/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/anilsurriya/received_events",
    type: "User",
    site_admin: false,
  },
];
